# Generated by Django 5.1.6 on 2025-03-24 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cliente', models.CharField(max_length=50, unique=True)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('telefono_cliente', models.CharField(max_length=15)),
                ('estado', models.CharField(choices=[('actualizado', 'Actualizado'), ('no_contactado', 'No Contactado'), ('formulario_enviado', 'Formulario Enviado'), ('no_proporciono_datos', 'No Proporcionó Datos')], max_length=50)),
                ('asignado_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quien_actualizo', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='clientes.cliente')),
            ],
        ),
    ]
