# Generated by Django 5.1.6 on 2025-03-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_asignacion',
            field=models.CharField(choices=[('asignado', 'Asignado'), ('no_asignado', 'No Asignado')], default='no_asignado', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_reporte',
            field=models.CharField(choices=[('sin_actualizar', 'Sin Actualizar'), ('actualizado', 'Actualizado'), ('no_contactado', 'No Contactado'), ('formulario_enviado', 'Formulario Enviado'), ('no_proporciono_datos', 'No Proporcionó Datos')], default='Sin Actualizar', max_length=50),
        ),
    ]
