# Generated by Django 5.1.6 on 2025-03-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_estado_cliente_estado_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contacto_cliente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
