# Generated by Django 5.1.6 on 2025-03-26 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_contacto_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 26, 21, 11, 58, 83811, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
