# Generated by Django 5.1.6 on 2025-03-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_detallecliente_created_at_detallecliente_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecliente',
            name='contacto_atendio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detallecliente',
            name='telefono_contacto_atendio',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
