# Generated by Django 5.1.6 on 2025-03-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_estadoreporte_alter_cliente_estado_reporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementstate',
            name='estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_reporte',
            field=models.CharField(choices=[('sin_actualizar', 'Sin Actualizar'), ('actualizado', 'Actualizado'), ('no_contactado', 'No Contactado'), ('formulario_enviado', 'Formulario Enviado'), ('no_proporciono_datos', 'No Proporcionó Datos')], default='Sin Actualizar', max_length=50),
        ),
        migrations.DeleteModel(
            name='EstadoReporte',
        ),
    ]
