# Generated by Django 5.1.6 on 2025-03-31 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_movementstate_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detallecliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='movementstate',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='movementstate',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ObservacionPredefinida',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='contador_reportes',
            new_name='veces_contactado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado_asignacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado_reporte',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='asignado_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto_cliente',
            field=models.CharField(default='Sin contacto', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(default='Nombre no registrado', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.CharField(default='0000-0000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.estadoreporte'),
        ),
        migrations.AddField(
            model_name='movimientoestado',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='movimientoestado',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.estadoreporte'),
        ),
        migrations.AddField(
            model_name='notamovimiento',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='clientes.movimientoestado'),
        ),
        migrations.DeleteModel(
            name='DetalleCliente',
        ),
        migrations.DeleteModel(
            name='MovementState',
        ),
    ]
