# Generated by Django 5.1.6 on 2025-04-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_estadoreporte_movimientoestado_notamovimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoreporte',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=50),
            preserve_default=False,
        ),
    ]
