# Generated by Django 5.1.6 on 2025-04-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_estadoreporte_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoreporte',
            name='intentos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
