# Generated by Django 5.1.6 on 2025-04-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_estadoreporte_intentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sin_contestar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
