# Generated by Django 5.1.6 on 2025-04-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_cliente_sin_contestar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultima_llamada_no_contesto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
