# Generated by Django 5.1.6 on 2025-04-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_cliente_ultima_llamada_no_contesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='formulario_sin_contestar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
