# Generated by Django 5.1.6 on 2025-04-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_cliente_formulario_sin_contestar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultimo_envio_formulario',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
