# Generated by Django 5.1.6 on 2025-04-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_cliente_asignado_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_actual',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.estadoreporte'),
        ),
    ]
