# Generated by Django 5.1.6 on 2025-04-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_cliente_correo_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoreporte',
            name='genera_movimiento',
            field=models.BooleanField(default=True),
        ),
    ]
