# Generated by Django 5.1.6 on 2025-04-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_historialestadosinmovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestadosinmovimiento',
            name='genera_movimiento',
            field=models.BooleanField(default=False),
        ),
    ]
